---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ cookiecutter.project_name }}'
rules:
  - apiGroups: ['kopf.dev']
    resources: ['clusterkopfpeerings']
    verbs: ['get', 'list', 'patch', 'watch']
  - apiGroups: ['apiextensions.k8s.io']
    resources: ['customresourcedefinitions']
    verbs: ['get', 'create', 'list', 'patch', 'watch']
  - apiGroups: ['']
    resources: ['namespaces']
    verbs: ['list', 'watch']
  - apiGroups: ['admissionregistration.k8s.io/v1', 'admissionregistration.k8s.io/v1beta1']
    resources: ['validatingwebhookconfigurations', 'mutatingwebhookconfigurations']
    verbs: ['create', 'patch']
  - apiGroups: ['{{ cookiecutter.crd_group }}']
    resources: ['{{ cookiecutter.crd_plural }}']
    verbs: ['list', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: '{{ cookiecutter.project_name }}'
  namespace: '{{ cookiecutter.project_name }}'
rules:
  - apiGroups: ['kopf.dev']
    resources: ['kopfpeerings']
    verbs: ['get', 'list', 'patch', 'watch']
  - apiGroups: ['']
    resources: ['events']
    verbs: ['create']
  - apiGroups: ['{{ cookiecutter.crd_group }}']
    resources: ['{{ cookiecutter.crd_plural }}']
    verbs: ['list', 'patch', 'watch']
  - apiGroups: ['batch', 'extensions']
    resources: ['jobs']
    verbs: ['create']
  - apiGroups: ['']
    resources: ['pods', 'persistentvolumeclaims']
    verbs: ['create']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: '{{ cookiecutter.project_name }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ cookiecutter.project_name }}'
subjects:
  - kind: ServiceAccount
    name: '{{ cookiecutter.project_name }}'
    namespace: '{{ cookiecutter.project_name }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: '{{ cookiecutter.project_name }}'
  namespace: '{{ cookiecutter.project_name }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ cookiecutter.project_name }}'
subjects:
  - kind: ServiceAccount
    name: '{{ cookiecutter.project_name }}'
    namespace: '{{ cookiecutter.project_name }}'
