# Local Cluster Configuration
# ---------------------------

apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: '{{ cookiecutter.project_name }}'
nodes:
  - role: control-plane
  - role: worker
  - role: worker
