---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ cookiecutter.project_name }}'
  namespace: '{{ cookiecutter.project_name }}'
spec:
  template:
    spec:
      containers:
        - name: 'operator'
          image: 'localhost:5000/{{ cookiecutter.project_name }}'
