# Custom Resource Definitions
# ---------------------------

# The following file defines the various custom resource definitions available
# to the operator.

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: '{{ cookiecutter.crd_plural }}.{{ cookiecutter.crd_group }}'
spec:
  group: '{{ cookiecutter.crd_group }}'
  names:
    categories:
      - all
    kind: '{{ cookiecutter.crd_kind }}'
    plural: '{{ cookiecutter.crd_plural }}'
    shortNames:
      - '{{ "".join(cookiecutter.crd_singular[0:3]) }}'
    singular: '{{ cookiecutter.crd_singular }}'
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Example String
          description: >-
            Replace this printer column with something a bit more useful.
          jsonPath: .spec.example_string
          priority: 0
          type: string
      schema:
        openAPIV3Schema:
          type: object
          description: >-
            A breif description of this custom resource.
          properties:
            spec:
              type: object
              description: >-
                Contains the complete specification of the custom resource.
              properties:
                example_string:
                  default: foo
                  description: >-
                    Replace this with something a bit more useful.
                  pattern: >-
                    ^(foo)|(bar)|(baz)$
                  type: string
                example_integer:
                  default: 5
                  description: >-
                    Replace this with something a bit more useful.
                  maximum: 10
                  minimum: 0
                  type: integer
